[project]
name = "lnbits-orangepiller"
version = "0.1.0"
requires-python = ">=3.10,<3.13"
description = "Onboard merchants to Bitcoin with managed LNbits accounts and payback arrangements"
authors = []
urls = { Repository = "https://github.com/lnbits/orangepiller" }

dependencies = [ "lnbits>1" ]

[tool.uv]
dev-dependencies = [
    "black",
    "pytest-asyncio",
    "pytest",
    "mypy",
    "pre-commit",
    "ruff",
]

[tool.pytest.ini_options]
log_cli = false
testpaths = [
  "tests"
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["F", "E", "W", "I", "A", "C", "N", "UP", "RUF", "B"]
ignore = ["C901"]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.pep8-naming]
classmethod-decorators = [
    "validator",
    "root_validator",
]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
    "fastapi.Depends",
    "fastapi.Query",
]
