#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Feature: Add npub Identifier Support to Nostr Notifications

set -e

echo "========================================"
echo "Starting LNbits Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if we're in the right directory
if [ ! -f "pyproject.toml" ]; then
    echo -e "${RED}Error: Must be run from LNbits project root${NC}"
    exit 1
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing Python dependencies..."
if command -v poetry &> /dev/null; then
    poetry install --quiet
    echo -e "${GREEN}Dependencies installed${NC}"
else
    echo -e "${RED}Poetry not found. Please install poetry first.${NC}"
    exit 1
fi

# ============================================
# ENVIRONMENT SETUP
# ============================================

echo ""
echo "Checking environment configuration..."

# Check for required Nostr environment variables
if [ -z "$LNBITS_NOSTR_NOTIFICATIONS_ENABLED" ]; then
    echo -e "${YELLOW}Warning: LNBITS_NOSTR_NOTIFICATIONS_ENABLED not set${NC}"
    echo "To test Nostr notifications, set: export LNBITS_NOSTR_NOTIFICATIONS_ENABLED=true"
fi

if [ -z "$LNBITS_NOSTR_NOTIFICATIONS_PRIVATE_KEY" ]; then
    echo -e "${YELLOW}Warning: LNBITS_NOSTR_NOTIFICATIONS_PRIVATE_KEY not set${NC}"
    echo "To test Nostr notifications, set this to an nsec private key"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting LNbits server..."

# Start LNbits in background
poetry run python -m lnbits &
LNBITS_PID=$!

# Wait for LNbits to be ready
echo "Waiting for LNbits to start on port 5002..."
MAX_WAIT=30
COUNT=0
while ! nc -z localhost 5002 2>/dev/null; do
    COUNT=$((COUNT + 1))
    if [ $COUNT -ge $MAX_WAIT ]; then
        echo -e "${RED}LNbits failed to start within ${MAX_WAIT} seconds${NC}"
        kill $LNBITS_PID 2>/dev/null
        exit 1
    fi
    sleep 1
done

echo -e "${GREEN}LNbits ready${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  LNbits:     http://localhost:5002"
echo "  API Docs:   http://localhost:5002/docs"
echo ""
echo "Account Settings (notifications): http://localhost:5002/account"
echo ""
echo "To stop the server, press Ctrl+C or run: kill $LNBITS_PID"
echo ""

# Keep script running to maintain server
wait $LNBITS_PID
